### PR TITLE
Setup GitHub Actions!

### PR DESCRIPTION
**Pull request by Aissaoui-Ahmed**

### CODE REVIEW

**Comment by atefBB** [comment]
<div dir="rtl">جزاكم الله خيرا، سألقي على هذا نظرة إن شا الله.</div>

**Comment by Aissaoui-Ahmed** [comment]
You can see [Actions](https://github.com/Aissaoui-Ahmed/quran-react-app/actions/runs/457044076) and [Deploy](https://github.com/Aissaoui-Ahmed/quran-react-app/commits/gh-pages) 
شكرا

**Review by celyes — CHANGES_REQUESTED** [review]
Correct typo in line 40: deloy ==> deploy

**Review by celyes — APPROVED** [review]

**Review by atefBB — COMMENTED** [review]
I'm using `yarn` so we don't need `package lock` file !

**Comment by Aissaoui-Ahmed** [comment]
> I'm using `yarn` so we don't need `package lock` file !

you can't run npm ci without package lock  👨🏽‍🚀 🧶

**Comment by atefBB** [comment]
> > I'm using `yarn` so we don't need `package lock` file !
> 
> you can't run npm ci without package lock  👨🏽‍🚀 🧶 

Ahaa, I don't know that. Thx.

**Pull request closed without merging**
